on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
 
name: "Build & Release"
 
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
 
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
 
      - name: Flutter pub get
        run: flutter pub get
 
      - name: Generate files (Build-Runner)
        run: flutter pub run build_runner build
 
      - name: Generate files from JSON
        env:
          ENV_PROD: ${{ secrets.ENV_PROD }}
        run: |
          if [[ -z "${ENV_PROD}" ]]; then
            echo "ENV_PROD secret is not set."
            exit 1
          fi
          curl -sSL --create-dirs -o env/prod.json "${ENV_PROD}"
 
      - name: Build APK
        run: flutter build apk --flavor production --dart-define-from-file=./env/prod.json --release
 
      - name: Upload APK as Release Asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
 
      - name: Convert APK to Base64
        id: base64_apk
        run: |
          base64 build/app/outputs/flutter-apk/app-production-release.apk > apk_base64.txt
          APK_BASE64=$(cat apk_base64.txt)
          echo "::set-output name=apk_base64::$APK_BASE64"
  
      - name: Send notification to Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          APK_BASE64=${{ steps.base64_apk.outputs.apk_base64 }}
          MESSAGE=$(cat <<EOF
          {
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "summary": "New APK Build",
            "sections": [{
                "activityTitle": "New Flutter APK Build",
                "activitySubtitle": "Build Successful",
                "text": "The APK file is attached below (base64 encoded).",
                "facts": [{
                    "name": "File Name:",
                    "value": "app-release.apk"
                }],
                "markdown": true
            }],
            "potentialAction": [{
                "@type": "OpenUri",
                "name": "Download APK",
                "targets": [{
                    "os": "default",
                    "uri": "data:application/vnd.android.package-archive;base64,$APK_BASE64"
                }]
            }]
          }
          EOF
          )
          curl -H "Content-Type: application/json" -d "$MESSAGE" $TEAMS_WEBHOOK_URL